trigger:
- master
- releases/*

stages:
- stage: 'BuildSharedNpm_Win'
  displayName: 'Windows - Build Shared Npm packages'
  dependsOn: []
  pool:
    vmImage: windows-2022
  condition: and(succeeded())
  jobs:
  - template: ci/build-common-packages.yml

- stage: 'BuildSharedNpm_Ubuntu'
  displayName: 'Ubuntu - Build Shared Npm packages'
  dependsOn: []
  pool:
    vmImage: 'ubuntu-20.04'
  condition: and(succeeded())
  jobs:
  - template: ci/build-common-packages.yml