trigger:
- master
- releases/*

stages:
- stage: 'BuildSharedNpmWin'
  displayName: 'Windows - Build Shared Npm packages'
  dependsOn: []
  pool:
    vmImage: windows-2022
  condition: succeeded()
  jobs:
  - template: ci/build-common-packages.yml

- stage: 'BuildSharedNpmUbuntu'
  displayName: 'Ubuntu - Build Shared Npm packages'
  dependsOn: []
  pool:
    vmImage: 'ubuntu-20.04'
  condition: succeeded()
  jobs:
  - template: ci/build-common-packages.yml