trigger:
- master
- releases/*

jobs:
- job: buildSharedNpm_win
  displayName: Build shared npm packages (Win)
  condition: and(succeeded(), not(variables.task), eq(variables.os, 'Windows_NT'))
  pool:
    vmImage: windows-2022
  steps:
  - template: ci/build-common-packages.yml